name: CI/CD Pipeline
# Nome do Workflow.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#Define quando o workflow deve ser executado.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build the application
      run: npm run build

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: echo "Deploying to production server..."

 #Define os trabalhos que serão executados.

